server:
  port : 8080
spring :
  application:
    name: ticket
  jpa :
    show-sql : true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2

eureka:
  client:
    service-url:
      default-zone: http://localhost:8762/eureka,http://localhost:8761/eureka
  instance:
    prefer-ip-address: true