spring:
  profiles: peer2
  application:
    name: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
#      default-zone: http://user:user@localhost:8761/eureka
